version: '3.8'

services:
  ai-security-guard:
    build: .
    container_name: ai_security_container
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./chroma_db:/app/chroma_db
      - ./models_cache:/app/models_cache  # Model buraya inecek, imajın içinde kalmayacak!
    restart: always